### ISSUE TITLE
Bug when trying to match container in rules

### ISSUE THREAD

**Issue by qjerome** [kunai-project/kunai#72]

**Comment by qjerome** [comment]
The way to go is:

```yaml
name: docker
params:
    filter: true
matches:
    $has_container: .info.host.container is some
    $is_docker: .info.host.container.type is 'docker'
condition: $has_container and $is_docker
```

**NB:** as `.info.host.container` may be `null`,  `$has_container` needs to be evaluated first and acts as a stop if `false`. It has to be there to prevent error messages to pop up.

cc: @davidszili @xme -> there is no release yet with that fix but if compiled from git it will work

**Comment by qjerome** [comment]
The way to go is:

```yaml
name: docker
params:
    filter: true
matches:
    $has_container: .info.host.container is some
    $is_docker: .info.host.container.type is 'docker'
condition: $has_container and $is_docker
```

**NB:** as `.info.host.container` may be `null`,  `$has_container` needs to be evaluated first and acts as a stop if `false`. It has to be there to prevent error messages to pop up.

cc: @davidszili @xme -> there is no release yet with that fix but if compiled from git it will work
